language: cpp
sudo: false


matrix:
  include:
    - os: linux
      dist: trusty
      compiler:
        - gcc
      before_install:
        # C++17
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update -qq
      install:
        # C++17
        - sudo apt-get install -qq g++-8
        - sudo apt install build-essential cmake git libcap-dev curl
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
      script:
        - make -j2
    - os: windows
      cache: false
      before_install:
        - git config --global core.autocrlf false
      install:
        - choco install msys2
      script:
        - mkdir -p build
        - cd build
        - c:/tools/msys64/msys2_shell.cmd -mingw64 -defterm -here -no-start ../travis-windows.sh
        - tasklist
        - travis_terminate 0
    - os: osx
      script:
        - make -j2
